version: '2'

services:

  nginx:
    build:
      context: .
      dockerfile: nginx/nginx.dockerfile
    links:
      - node1:node1
      - node2:node2
    depends_on:
      - node1
      - node2
    ports:
      - "80:80"
    networks:
      - app-network

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000"
    environment:
      - INSTANCE=node1
    networks:
      - app-network

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000"
    environment:
      - INSTANCE=node2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
